| memberId | 发消息者ID | 无 |
| type | 发送人类型，默认0,一般用户 | 无 |
| sendtype | 发送类型，提问还是一般消息，默认0,一般消息 | 无 |
| messagetype | 消息类型 | 无 |
| date | 发表日期 | 无 |
| content | 内容 | 无 |
| parentId | 回复互动的ID,默认0 | 无 |
| memberId | 分析师ID | 无 |
| teamId | 团队ID | 无 |
| code | 商品代码 | 无 |
| commodityId | 商品ID | 无 |
| bsFlag | 买卖标识(多,空) | 无 |
| seFlag | 委托标识(建,平) | 无 |
| price | 成交价格 | 无 |
| tradeType | 成交类型(指价,市价) | 无 |
| date | 喊单时间 | 无 |
| stopProfit | 止盈 | 无 |
| stopLoss | 止损 | 无 |
| positions | 仓位 | 无 |
| profit | 盈利 | 无 |

