drop table report_frimfunds         ;
drop table report_fundio          ;
drop table report_fundio_history  ;
drop table report_holding         ;
drop table report_holding_history ;
drop table report_order           ;
drop table report_order_history   ;
drop table report_trade           ;
drop table report_trade_history   ;
